import React, { useEffect, useState, useRef } from "react";
import { licenses } from "../../js/licenseOptions.js";
import GlobalVariables from "../../js/globalvariables.js";
import Molecule from "../../molecules/molecule.js";
import { useNavigate } from "react-router-dom";
import CreatableSelect from "react-select/creatable";
import topics from "../../js/maslowTopics.js";
import { re } from "mathjs";
//Replaces the loaded projects if the user clicks on new project button
const NewProjectPopUp = (props) => {
  /**
   * The name of the current user.
   * @type {string}
   */
  var currentUser = null;
  /**
   * The name of the current repo.
   * @type {string}
   */
  var currentRepoName = null;
  /**
   * The text to display at the top of the bill of materials.
   * @type {string}
   */
  var bomHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model \n# Bill Of Materials \n |Part|Number Needed|Price|Source| \n |----|----------|-----|-----|";
  /**
   * The text to display at the top of the ReadMe file.
   * @type {string}
   */
  var readmeHeader =
    "###### Note: Do not edit this file directly, it is automatically generated from the CAD model";

  /**
   * The authorized user octokit object.
   * @type {object}
   */
  const authorizedUserOcto = props.authorizedUserOcto;
  const setExportPopUp = props.setExportPopUp;
  const exporting = props.exporting;

  const keys_ar = [];
  Object.keys(licenses).forEach((key) => {
    keys_ar.push(key);
  });

  const navigate = useNavigate();
  const projectRef = useRef();
  const projectTopicRef = useRef();
  const projectDescriptionRef = useRef();
  const projectLicenseRef = useRef();
  const projectUnitsRef = useRef();
  const [pending, setPending] = useState(false); // useFormStatus(); in the future

  //Progress bar for creating a new project
  const [newProjectBar, setNewProjectBar] = useState(0);

  /**
   * Create a new project or exports current molecule to github and navigate to new project create page
   * * @param {string} name - Project Name
   * @param {array} topics - Array of topics
   * @param {string} description - Project Description
   * @param {object} molecule - If there's an existing molecule to export
   * @param {boolean} exporting - If exporting a molecule
   *
   */
  const createProject = async (
    [name, topics, description, license, units],
    molecule,
    exporting
  ) => {
    //topics.push("abundance-project");
    // If there is a molecule and we are exporting replace current top molecule
    if (molecule !== undefined && exporting) {
      GlobalVariables.topLevelMolecule = molecule;
      molecule.topLevel = true; //force the molecule to export in the long form as if it were the top level molecule
    } else {
      //Load a blank project
      GlobalVariables.topLevelMolecule = new Molecule({
        x: 0,
        y: 0,
        topLevel: true,
        name: name,
        atomType: "Molecule",
        uniqueID: GlobalVariables.generateUniqueID(),
        unitsKey: units,
      });
    }
    GlobalVariables.currentMolecule = GlobalVariables.topLevelMolecule;

    await authorizedUserOcto
      .request("POST /user/repos", {
        name: name,
        description: description,
        headers: {
          "X-GitHub-Api-Version": "2022-11-28",
        },
      })
      .catch((err) => {
        window.alert(
          "Error creating project. That name might be taken already. Please try again with a different name."
        );
        setPending(false);
      })
      .then((result) => {
        setNewProjectBar(10);
        //Once we have created the new repo we need to create a file within it to store the project in
        currentRepoName = result.data.name;
        currentUser = GlobalVariables.currentUser;

        var jsonRepOfProject = GlobalVariables.topLevelMolecule.serialize();

        jsonRepOfProject.filetypeVersion = 1;
        const projectContent = window.btoa(
          JSON.stringify(jsonRepOfProject, null, 4)
        );

        /*aws dynamo post*/

        const apiUrl =
          "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage//post-new-project";
        fetch(apiUrl, {
          method: "POST",
          body: JSON.stringify({
            owner: result.data.owner.login,
            ranking: result.data.stargazers_count,
            repoName: result.data.name,
            forks: result.data.forks_count,
            topMoleculeID: GlobalVariables.topLevelMolecule.uniqueID,
            topics: topics,
            html_url: result.data.html_url,
            readme:
              "https://raw.githubusercontent.com/" +
              result.data.full_name +
              "/master/README.md?sanitize=true",
            contentURL:
              "https://raw.githubusercontent.com/" +
              result.data.full_name +
              "/master/project.abundance?sanitize=true",
            githubMoleculesUsed: [],
            svgURL:
              "https://raw.githubusercontent.com/" +
              result.data.full_name +
              "/master/project.svg?sanitize=true",
            dateCreated: result.data.created_at,
          }),
          headers: {
            "Content-type": "application/json; charset=UTF-8",
          },
        }).then((response) => {
          console.log(response);
        });

        //Create the project file

        authorizedUserOcto.rest.repos
          .createOrUpdateFileContents({
            owner: currentUser,
            repo: currentRepoName,
            path: "project.abundance",
            message: "Initialize repo",
            content: projectContent,
          })
          .then((result) => {
            setNewProjectBar(20);
            //Then create the BOM file
            var content = window.btoa(bomHeader); // create a file with just the header in it and base64 encode it
            authorizedUserOcto.rest.repos
              .createOrUpdateFileContents({
                owner: currentUser,
                repo: currentRepoName,
                path: "BillOfMaterials.md",
                message: "initialize BOM",
                content: content,
              })
              .then(() => {
                setNewProjectBar(30);
                //Then create the README file
                content = window.btoa(readmeHeader); // create a file with just the word "init" in it and base64 encode it
                authorizedUserOcto.rest.repos
                  .createOrUpdateFileContents({
                    owner: currentUser,
                    repo: currentRepoName,
                    path: "README.md",
                    message: "initialize README",
                    content: content,
                  })
                  .then(() => {
                    setNewProjectBar(40);
                    authorizedUserOcto.rest.repos
                      .createOrUpdateFileContents({
                        owner: currentUser,
                        repo: currentRepoName,
                        path: "project.svg",
                        message: "SVG Picture",
                        content: "",
                      })
                      .then(() => {
                        setNewProjectBar(50);
                        authorizedUserOcto.rest.repos
                          .createOrUpdateFileContents({
                            owner: currentUser,
                            repo: currentRepoName,
                            path: ".gitattributes",
                            message: "Create gitattributes",
                            content: window.btoa("data binary"),
                          })
                          .then(() => {
                            setNewProjectBar(60);
                            authorizedUserOcto.rest.repos
                              .createOrUpdateFileContents({
                                owner: currentUser,
                                repo: currentRepoName,
                                path: "data.json",
                                message: "Data file",
                                content: "",
                              })
                              .then(() => {
                                setNewProjectBar(80);
                                let licenseText = ""; // ?
                                authorizedUserOcto.rest.repos
                                  .createOrUpdateFileContents({
                                    owner: currentUser,
                                    repo: currentRepoName,
                                    path: "LICENSE.txt",
                                    message: "Establish license",
                                    content: window.btoa(
                                      GlobalVariables.toBinaryStr(
                                        licenses[license]
                                      )
                                    ),
                                  })
                                  .then(() => {
                                    setNewProjectBar(90);

                                    authorizedUserOcto.rest.repos
                                      .replaceAllTopics({
                                        owner: currentUser,
                                        repo: currentRepoName,
                                        names: topics,
                                      })
                                      .then(() => {
                                        //GET the new repo from aws and set it as the current repo
                                        let query =
                                          "attribute=repoName" +
                                          "&query=" +
                                          currentRepoName +
                                          "&user=" +
                                          currentUser;

                                        const scanApiUrl =
                                          "https://hg5gsgv9te.execute-api.us-east-2.amazonaws.com/abundance-stage/scan-search-abundance?" +
                                          query +
                                          "&lastKey";

                                        fetch(scanApiUrl).then((awsRepos) => {
                                          let newRepo;
                                          awsRepos.json().then((data) => {
                                            newRepo = data["repos"][0];
                                            GlobalVariables.currentRepo =
                                              newRepo;
                                            setExportPopUp(false);
                                            navigate(
                                              `/${GlobalVariables.currentRepo.owner}/${GlobalVariables.currentRepo.repoName}`
                                            );
                                          });
                                        });
                                      });
                                  });
                              });
                          });
                      });
                  });
              });
          });
      });
  };

  /* Handles form submission for create new/ export project form */
  const handleSubmit = async (e) => {
    e.preventDefault();
    setPending(true);
    const projectName = projectRef.current.value;
    const projectTopicArray = projectTopicRef.current.getValue();
    const projectDescription = projectDescriptionRef.current.value;
    const projectTopic = [];
    const projectLicense = projectLicenseRef.current.value;
    const projectUnits = projectUnitsRef.current.value;

    projectTopicArray.forEach((topic) => {
      projectTopic.push(topic[`value`]);
    });

    if (GlobalVariables.currentMolecule) {
      var molecule = GlobalVariables.currentMolecule;
    }
    // Calls the create new project function and creates a new github repo with user input
    createProject(
      [
        projectName,
        projectTopic,
        projectDescription,
        projectLicense,
        projectUnits,
      ],
      molecule,
      exporting
    );
  };

  return (
    <>
      <div className="login-page export-div">
        <div className="form animate fadeInUp one">
          <button
            style={{ width: "3%", display: "block" }}
            onClick={() => {
              setExportPopUp(false);
            }}
            className="closeButton"
          >
            <img></img>
          </button>
          <form
            onSubmit={(e) => {
              handleSubmit(e);
            }}
          >
            <h2>
              {exporting
                ? "Export this molecule to Github"
                : "Create a New Project"}
            </h2>
            <label htmlFor="project-name">Project Name</label>
            <input
              name="Project Name"
              placeholder="Project Name"
              ref={projectRef}
              required
            />
            <label htmlFor="license-options">License</label>
            <select id="license-options" ref={projectLicenseRef}>
              {keys_ar.map((opt) => {
                return (
                  <option key={opt} value={opt}>
                    {opt}
                  </option>
                );
              })}
            </select>
            <label htmlFor="measure-units">Units</label>
            <select id="measure-units" ref={projectUnitsRef}>
              <option key={"inchesop"} value={"Inches"}>
                Inches
              </option>
              <option key={"millop"} value={"MM"}>
                MM
              </option>
            </select>
            <label htmlFor="project-description">Project Description</label>
            <input
              placeholder="Project Description"
              ref={projectDescriptionRef}
            />
            <label htmlFor="project-topics">Project Topics</label>
            <CreatableSelect
              defaultValue={[]}
              isMulti
              name="Project Topics"
              options={topics}
              className="basic-multi-select"
              classNamePrefix="select"
              ref={projectTopicRef}
            />
            <button className="submit-button" disabled={pending} type="submit">
              {pending ? newProjectBar + "%" : "Submit/Export to Github"}
            </button>
          </form>
        </div>
      </div>
    </>
  );
};

export default NewProjectPopUp;
