import Molecule from '../molecules/molecule.js'
import GlobalVariables from './globalvariables.js'
import { licenses } from './licenseOptions.js'
import { extractBomTags, convertLinks } from './BOM.js'
import { OAuth } from 'oauthio-web'
import { Octokit} from "https://esm.sh/octokit@2.0.19"
import { re } from 'mathjs'
//import createOAuthUserAuth from "@octokit/auth-oauth-user"

/**
 * This function works like a class to sandbox interaction with GitHub.
 */
export default function GitHubModule(){
    //const { Octokit } = require("@octokit/rest")
    /** 
     * The octokit instance which allows authenticated interaction with GitHub.
     * @type {object}
     */
    var octokit = null//new Octokit()
    
    /** 
     * The HTML element which is the popup.
     * @type {object}
     */
    var popup = null;//document.getElementById('projects-popup')
    /** 
     * The name of the current repo.
     * @type {string}
     */
    var currentRepoName = null
    /** 
     * The name of the currently logged in user.
     * @type {string}
     */
    var currentUser = null
    /** 
     * The text to display at the top of the bill of materials.
     * @type {string}
     */
    var bomHeader = "###### Note: Do not edit this file directly, it is automatically generated from the CAD model \n# Bill Of Materials \n |Part|Number Needed|Price|Source| \n |----|----------|-----|-----|"
     
    /** 
     * The text to display at the top of the ReadMe file.
     * @type {string}
     */
    var readmeHeader = "###### Note: Do not edit this file directly, it is automatically generated from the CAD model"

    /** 
     * The timer used to trigger saving of the file.
     * @type {object}
     */
    var intervalTimer

    /** 
     * The timer used to trigger saving of the file.
     * @type {object}
     */
    var page = 1
    

    
    /** 
     * Runs when you click on a project.
     */
    this.projectClicked = function(projectName, projectID, owned){
        //runs when you click on one of the projects
        if(projectName == "New Project"){
            this.createNewProjectPopup()
        }
        else if(owned){
            this.loadProject(projectName)
        }
        else{
            window.open('/run?'+projectID)
        }
    }
    
    /** 
     * Runs owned search first and then full github search
     
    this.openTab = function(page) {

        // Show the current tab, and add an "active" class to the button that opened the tab
        //Click on the search bar so that when you start typing it shows updateCommands
        document.getElementById('menuInput').focus()
        
        this.loadProjectsBySearch("yoursButton", {key: "Enter"}, document.getElementById("project_search").value, "updated", page, true)
            .then( () => {
                this.loadProjectsBySearch("githubButton", {key: "Enter"}, document.getElementById("project_search").value, "stars", page, false)
            })
    }
    */
    /** 
     * The popup to create a new project (giving it a name and whatnot).
     
    this.createNewProjectPopup = function(){
        //Clear the popup and populate the fields we will need to create the new repo
        
        while (popup.firstChild) {
            popup.removeChild(popup.firstChild)
        }
        popup.setAttribute("style", "padding:2% 0")
        //Project name
        // <div class="form">
        var createNewProjectDiv = document.createElement("DIV")
        createNewProjectDiv.setAttribute("class", "form")
        createNewProjectDiv.setAttribute("style", "color:whitesmoke")

        
        //Grab all of the available licenses
        var licenseOptions = document.createElement('select')
        licenseOptions.setAttribute("id", "license-options")
        Object.keys(licenses).forEach( key => {
            var option = document.createElement('option')
            option.value = key
            option.text = key
            licenseOptions.appendChild(option)
        })
        
        form.appendChild(licenseOptions)
        
        //Add the button
        var createButton = document.createElement("button")
        createButton.setAttribute("type", "button")
        createButton.setAttribute("style", "height: 50px; border: 1px solid whitesmoke;")
        createButton.addEventListener('click', () => {
            this.createNewProject()
        })
        var buttonText = document.createTextNode("Create Project")
        createButton.appendChild(buttonText)
        form.appendChild(createButton)
    
        popup.appendChild(createNewProjectDiv)

    }
    */
    /** 
     * Open a new tab with a sharable copy of the project.
     
    this.shareOpenedProject = function(){
        alert("A page with a shareable url to this project will open in a new window. Share the link to that page with anyone you would like to share the project with.")
         

        octokit.repos.get({
            owner: currentUser,
            repo: currentRepoName
        }).then(result => {
            var ID = result.data.id
            window.open('/run?'+ID)
        })
    }

    
    /** 
     * Open a new tab with the github page for the project.
    
    this.openGitHubPage = function(){
        //Open the github page for the current project in a new tab
        octokit.repos.get({
            owner: currentUser,
            repo: currentRepoName
        }).then(result => {
            var url = result.data.html_url
            window.open(url)
        })
    }
     */
    /** 
     * Search github for projects which match a string.
    
    this.searchGithub = async (searchString,owned) => {
        //Load projects
        var query

        if(owned){
            query = searchString + ' ' + 'user:' + currentUser + ' topic:maslowcreate'
        }
        else{
            query = searchString + ' topic:maslowcreate -user:' + currentUser
        }

        return await octokit.search.repos({
            q: query,
            sort: 'stars',
            per_page: 10,
            page: 1,
            headers: {
                accept: 'application/vnd.github.mercy-preview+json'
            }
        })
    }
     */
   
  
    
    /** 
     * Creates a new blank project.
     */
    this.createNewProject = function(){

        if(typeof intervalTimer != undefined){
            clearInterval(intervalTimer) //Turn of auto saving
        }
        
        //Get name and description
        const name = document.getElementById('project-name').value
        const description = document.getElementById('project-description').value
        const licenseText = licenses[document.getElementById('license-options').value]
        //Load a blank project
        GlobalVariables.topLevelMolecule = new Molecule({
            x: 0, 
            y: 0, 
            topLevel: true, 
            name: name,
            atomType: "Molecule",
            uniqueID: GlobalVariables.generateUniqueID()
        })
        
        GlobalVariables.currentMolecule = GlobalVariables.topLevelMolecule
      
        //Create a new repo
  // Use popup for oauth
  OAuth.popup("github").then((github) => {
    /**
     * Oktokit object to access github
     * @type {object}
     */
    octokit = new Octokit({
      auth: github.access_token,
    });
  });
    octokit.request("POST /user/repos", {
    name: "Hello-World",
    description: "This is your first repo!",
    homepage: "https://github.com",
    private: false,
    is_template: true,
    headers: {
      "X-GitHub-Api-Version": "2022-11-28",
    }
  }).then(result => {
            //Once we have created the new repo we need to create a file within it to store the project in
            currentRepoName = result.data.name
            var jsonRepOfProject = GlobalVariables.topLevelMolecule.serialize()
            jsonRepOfProject.filetypeVersion = 1
            jsonRepOfProject.circleSegmentSize = GlobalVariables.circleSegmentSize
            const projectContent = window.btoa(JSON.stringify(jsonRepOfProject, null, 4))
            
            octokit.repos.createOrUpdateFileContents({
                owner: currentUser,
                repo: currentRepoName,
                path: "project.maslowcreate",
                message: "initialize repo", 
                content: projectContent
            }).then(() => {
                //Then create the BOM file
                var content = window.btoa(bomHeader) // create a file with just the header in it and base64 encode it
                octokit.repos.createOrUpdateFileContents({
                    owner: currentUser,
                    repo: currentRepoName,
                    path: "BillOfMaterials.md",
                    message: "initialize BOM", 
                    content: content
                }).then(() => {
                    //Then create the README file
                    content = window.btoa(readmeHeader) // create a file with just the word "init" in it and base64 encode it
                    octokit.repos.createOrUpdateFileContents({
                        owner: currentUser,
                        repo: currentRepoName,
                        path: "README.md",
                        message: "initialize README", 
                        content: content
                    }).then(() => {
                        octokit.repos.createOrUpdateFileContents({
                            owner: currentUser,
                            repo: currentRepoName,
                            path: "project.svg",
                            message: "SVG Picture", 
                            content: ""
                        }).then(()=>{
                            octokit.repos.createOrUpdateFileContents({
                                owner: currentUser,
                                repo: currentRepoName,
                                path: ".gitattributes",
                                message: "Create gitattributes", 
                                content: window.btoa("data binary")
                            }).then(()=>{
                                octokit.repos.createOrUpdateFileContents({ 
                                    owner: currentUser,
                                    repo: currentRepoName,
                                    path: "data.json",
                                    message: "Data file", 
                                    content: ""
                                }).then(()=>{
                                    octokit.repos.createOrUpdateFileContents({ 
                                        owner: currentUser,
                                        repo: currentRepoName,
                                        path: "LICENSE.txt",
                                        message: "Establish license", 
                                        content:  window.btoa(licenseText)
                                    }).then(()=>{
                                        intervalTimer = setInterval(() => { this.saveProject() }, 1200000) //Save the project regularly
                                    })
                                })
                            })
                        })
                    })
                })
            })
            
            //Update the project topics
            octokit.repos.replaceAllTopics({
                owner: currentUser,
                repo: currentRepoName,
                names: ["maslowcreate", "maslowcreate-project"],
                headers: {
                    accept: 'application/vnd.github.mercy-preview+json'
                }
            })
        })
        
        GlobalVariables.currentMolecule.backgroundClick()
        
        //Clear and hide the popup
        while (popup.firstChild) {
            popup.removeChild(popup.firstChild)
        }
        popup.classList.add('off')
        
        
    }

    /** 
     * Save the current project to github.
     */
    this.saveProject = function(){
        //Save the current project into the github repo
        if(GlobalVariables.currentRepoName != null){
            
            //Store the target repo incase a new project is loaded during the save
            const saveRepoName = GlobalVariables.currentRepoName
            const saveUser = GlobalVariables.currentUser
            
            if(typeof intervalTimer != undefined){
                clearInterval(intervalTimer) //Turn off auto saving to prevent it from saving again during this save
            }
            //this.progressSave(0)
            // var shape = null

            // if(GlobalVariables.topLevelMolecule.value != null && typeof GlobalVariables.topLevelMolecule.value != 'number'){
            // shape = GlobalVariables.topLevelMolecule.value
            // }
            
            const passBOMOn = (bomItems) => {
                const values = {op: "svg", readPath: GlobalVariables.topLevelMolecule.path}
                console.log(window)
                const {answer} = window.ask(values)
                answer.then( answer => {
                    //this.progressSave(10)
                    
                    var contentSvg = answer //Would compute the svg picture here
                    
                    var bomContent = bomHeader
                    
                    var totalParts = 0
                    var totalCost  = 0
                    if(bomItems != undefined){
                        bomItems.forEach(item => {
                            totalParts += item.numberNeeded
                            totalCost  += item.costUSD
                            bomContent = bomContent + "\n|" + item.BOMitemName + "|" + item.numberNeeded + "|$" + item.costUSD.toFixed(2) + "|" + convertLinks(item.source) + "|"
                        })
                    }
                    bomContent = bomContent + "\n|" + "Total: " + "|" + totalParts + "|$" + totalCost.toFixed(2) + "|" + " " + "|"
                    bomContent = bomContent+"\n\n 3xCOG MSRP: $" + (3*totalCost).toFixed(2)
                    
                    var readmeContent = readmeHeader + "\n\n" + "# " + saveRepoName + "\n\n![](/project.svg)\n\n"
                    GlobalVariables.topLevelMolecule.requestReadme().forEach(item => {
                        readmeContent = readmeContent + item + "\n\n\n"
                    })
                        
                    var jsonRepOfProject = GlobalVariables.topLevelMolecule.serialize()
                    jsonRepOfProject.filetypeVersion = 1
                    jsonRepOfProject.circleSegmentSize = GlobalVariables.circleSegmentSize
                    const projectContent = JSON.stringify(jsonRepOfProject, null, 4)
                           
                    var decoder = new TextDecoder('utf8')
                    var finalSVG = decoder.decode(contentSvg)
                    
                    
                    const askJsonVals = {op: "getJSON", readPath: GlobalVariables.topLevelMolecule.path}
                    const  {answer: answer2} = window.ask(askJsonVals)
                    answer2.then( JSONData => {
                        
                        this.createCommit(octokit,{
                            owner: saveUser,
                            repo: saveRepoName,
                            changes: {
                                files: {
                                    'BillOfMaterials.md': bomContent,
                                    'README.md': readmeContent,
                                    'project.svg': finalSVG,
                                    'project.maslowcreate': projectContent,   
                                },
                                commit: 'Autosave'
                            }
                        })
                    })

                    intervalTimer = setInterval(() => this.saveProject(), 1200000)
                })
            }
            extractBomTags(GlobalVariables.topLevelMolecule.path, passBOMOn)
        }
    }
    
    /** 
     * Creates saving/saved pop up
     */
    this.progressSave = function (progress, saving = true) {
        
        progress = Math.max(0, progress) //Make it so the progress can't be displayed negitive
        
        var popUp = document.getElementById("popUp")   
        let popUpBox = document.querySelector('#Progress_Status') 
        //var width = 1; 
        popUp.setAttribute("style","display:block")
        popUpBox.setAttribute("style","display:block")
        
        if (progress >= 100) { 
            popUp.style.width = progress + '%' 
            if(saving){
                popUp.textContent = "Project Saved"
                setTimeout(function() {
                    popUp.setAttribute("style","display:none")
                    popUpBox.setAttribute("style","display:none")
                }, 4000)
            }
            else{
                popUp.setAttribute("style","display:none")
                popUpBox.setAttribute("style","display:none")
            }
        } else { 
            if(saving){
                popUp.textContent = "Saving..."
            }
            else{
                popUp.textContent = "Loading..."+progress.toFixed(1)+"%"
            }
            popUp.style.width = progress + '%'  
        } 
    } 
        
    /** 
     * Create a commit as part of the saving process.
     */
    this.createCommit = async function(octokit, { owner, repo, base, changes }) {
        //this.progressSave(30)
        let response
        
        if (!base) {
            response = await octokit.repos.get({ owner, repo })
            base = response.data.default_branch
        }
       //this.progressSave(40)
        
        response = await octokit.repos.listCommits({
            owner,
            repo,
            sha: base,
            per_page: 1
        })
        
        let latestCommitSha = response.data[0].sha
        const treeSha = response.data[0].commit.tree.sha
        //this.progressSave(60)
      
        response = await octokit.git.createTree({
            owner,
            repo,
            base_tree: treeSha,
            tree: Object.keys(changes.files).map(path => {
                if(changes.files[path] != null){
                    return {
                        path,
                        mode: '100644',
                        content: changes.files[path]
                    }
                }
                else{
                    return {
                        path,
                        mode: '100644',
                        sha: null
                    }
                }
            })
        })
        const newTreeSha = response.data.sha
        //this.progressSave(80)

        response = await octokit.git.createCommit({
            owner,
            repo,
            message: changes.commit,
            tree: newTreeSha,
            parents: [latestCommitSha]
        })
        latestCommitSha = response.data.sha

        //this.progressSave(90)
      
        await octokit.git.updateRef({
            owner,
            repo,
            sha: latestCommitSha,
            ref: "heads/" + base,
            force: true
        })
        //this.progressSave(100)
        console.warn("Project saved")
       
    }
    
    /** 
     * Loads a project from github by name.
     */
    this.loadProject = async function(project){
        
        console.log("project clicked: "+ project)

        this.totalAtomCount = 0
        this.numberOfAtomsToLoad = 0

        GlobalVariables.startTime = new Date().getTime()
        
        if(typeof intervalTimer != undefined){
            clearInterval(intervalTimer) //Turn off auto saving
        }

        //Clear and hide the popup
       /* while (popup.firstChild) {
            popup.removeChild(popup.firstChild)
        }
        popup.classList.add('off')
        */
        currentRepoName = project.name
        //Load a blank project
        GlobalVariables.topLevelMolecule = new Molecule({
            x: 0, 
            y: 0, 
            topLevel: true, 
            atomType: "Molecule"
        })
        
        GlobalVariables.currentMolecule = GlobalVariables.topLevelMolecule
        
        octokit.request('GET /repos/{owner}/{repo}/contents/{path}', {
            owner: project.owner,
            repo: project.name,
            path: 'project.maslowcreate'
        }).then(response => {
          console.log("Response: ")
          console.log(response)
        })  
        /*octokit.repos.getContent({
            owner: currentUser,
            repo: projectName,
            path: 'project.maslowcreate'
        }).then(result => {
            //content will be base64 encoded
            let rawFile = JSON.parse(atob(result.data.content))
            
            if(rawFile.circleSegmentSize){
                GlobalVariables.circleSegmentSize = rawFile.circleSegmentSize
            }
            
            if(rawFile.filetypeVersion == 1){
                GlobalVariables.topLevelMolecule.deserialize(rawFile)
            }
            else{
                GlobalVariables.topLevelMolecule.deserialize(this.convertFromOldFormat(rawFile))
            }
        })*/
        /*octokit.repos.get({
            owner: currentUser,
            repo: currentRepoName
        }).then(result => {
            GlobalVariables.fork = result.data.fork
            if(!GlobalVariables.fork){
                document.getElementById("pull_top").style.display = "none"
            }
            else{
                document.getElementById("pull_top").style.display = "inline"
            }
        })*/
        
    }
    
    this.convertFromOldFormat = function(json){
        
        var listOfMoleculeAtoms = json.molecules
        
        //Find the top level molecule
        var projectObject = listOfMoleculeAtoms.filter((molecule) => { return molecule.topLevel == true })[0]
        //Remove that element from the listOfMoleculeAtoms
        listOfMoleculeAtoms.splice(listOfMoleculeAtoms.findIndex(e => e.topLevel == true),1)
        
        //Recursive function to walk the tree and find molecule placeholders
        function walkForMolecules(projectObject){
            projectObject.allAtoms.forEach(function(atom, allAtomsIndex, allAtomsObject) {
                if(atom.atomType == "Molecule"){
                    
                    if(atom.allAtoms != undefined){ //If this molecule has allAtoms
                        walkForMolecules(atom)//Walk it
                    }
                    else{ //Else replace it with a version which does have allAtoms from the list
                        //Find the version in molecules list and plug it in
                        allAtomsObject[allAtomsIndex] = listOfMoleculeAtoms.filter((molecule) => { return molecule.uniqueID == atom.uniqueID })[0]
                        //Remove that element from the listOfMoleculeAtoms
                        listOfMoleculeAtoms.splice(listOfMoleculeAtoms.findIndex(e => e.uniqueID == atom.uniqueID),1)
                    }
                }
            })
        }
        
        //Find any placeholder molecules in there (this needs to be a full tree walk for everything to work)
        while(listOfMoleculeAtoms.length > 0){
            walkForMolecules(projectObject)
        }
        
        return projectObject
    }
    
    /** 
     * Begins the automatic process of saving the project
     */
    this.beginAutosave = function(){
        intervalTimer = setInterval(() => this.saveProject(), 120000) //Save the project regularly
    }
    
    /** 
     * Loads a project from github by its github ID.
     */
    this.getProjectByID = async function(id, saveUserInfo){
        let repo = await octokit.request('GET /repositories/:id', {id})
        //Find out the owners info;
        const user     = repo.data.owner.login
        const repoName = repo.data.name
        const description = repo.data.description
        //Get the file contents
        let result = await octokit.repos.getContent({
            owner: user,
            repo: repoName,
            path: 'project.maslowcreate'
        })
        
        //If this is the top level we will save the rep info at the top level
        if(saveUserInfo){
            currentUser = user
            currentRepoName = repoName
        }
        
        let rawFile = JSON.parse(atob(result.data.content))
        
        rawFile.description = description
        
        if(rawFile.filetypeVersion == 1){
            return rawFile
        }
        else{
            return this.convertFromOldFormat(rawFile)
        }
    }
    
    /** 
     * Loads a project's data from github by its github ID.
     */
    this.getProjectDataByID = async function(id){
        let repo = await octokit.request('GET /repositories/:id', {id})
        //Find out the owners info;
        const user     = repo.data.owner.login
        const repoName = repo.data.name
        
        try{
            let jsonData = await octokit.repos.getContent({
                owner: user,
                repo: repoName,
                path: 'data.json'
            })
            
            jsonData = atob(jsonData.data.content)
            return jsonData
            
        }catch(err){
            console.warn("Unable to load project data from github...using full model")
            return false
        }
    }
    
    /** 
     * Export a molecule as a new github project.
     */
    this.exportCurrentMoleculeToGithub = function(molecule){
        
        //Get name and description
        var name = molecule.name
        var description = "A stand alone molecule exported from Maslow Create"
        
        //Create a new repo
        octokit.repos.createForAuthenticatedUser({
            name: name,
            description: description
        }).then(result => {
            //Once we have created the new repo we need to create a file within it to store the project in
            var repoName = result.data.name
            var id       = result.data.id
            var path     = "project.maslowcreate"
            var content  = window.btoa("init") // create a file with just the word "init" in it and base64 encode it
            octokit.repos.createOrUpdateFileContents({
                owner: currentUser,
                repo: repoName,
                path: path,
                message: "initialize repo", 
                content: content
            }).then(() => {
                
                //Save the molecule into the newly created repo
                
                var path = "project.maslowcreate"
                
                molecule.topLevel = true //force the molecule to export in the long form as if it were the top level molecule
                var content = window.btoa(JSON.stringify(molecule.serialize({molecules: []}), null, 4)) //Convert the passed molecule object to a JSON string and then convert it to base64 encoding
                
                //Get the SHA for the file
                octokit.repos.getContent({
                    owner: currentUser,
                    repo: repoName,
                    path: path
                }).then(result => {
                    var sha = result.data.sha
                    
                    //Save the repo to the file
                    octokit.repos.updateFile({
                        owner: currentUser,
                        repo: repoName,
                        path: path,
                        message: "export Molecule", 
                        content: content,
                        sha: sha
                    }).then(() => {
                        //Replace the existing molecule now that we just exported
                        molecule.replaceThisMoleculeWithGithub(id)
                    })
                })

            })
            
            //Update the project topics
            octokit.repos.replaceTopics({
                owner: currentUser,
                repo: repoName,
                names: ["maslowcreate", "maslowcreate-molecule"],
                headers: {
                    accept: 'application/vnd.github.mercy-preview+json'
                }
            })
            
        })
    }

    /** 
     * Like a project on github by unique ID.
     */
    this.starProject = function(id){
        //Authenticate - Initialize with OAuth.io app public key
        OAuth.initialize('BYP9iFpD7aTV9SDhnalvhZ4fwD8')
        // Use popup for oauth
        OAuth.popup('github').then(github => {

            octokit = new Octokit({
                auth: github.access_token
            })
            
            octokit.request('GET /repositories/:id', {id}).then(result => {
                //Find out the information of who owns the project we are trying to like
                
                var user     = result.data.owner.login
                var repoName = result.data.name
                
                octokit.repos.listTopics({
                    owner: user, 
                    repo: repoName,
                    headers: {
                        accept: 'application/vnd.github.mercy-preview+json'
                    }
                }).then(()=> { 
                    //Find out if the project has been starred and unstar if it is
                    octokit.activity.checkStarringRepo({
                        owner:user,
                        repo: repoName
                    }).then(() => { 
                        var button= document.getElementById("Star-button")
                        button.setAttribute("class","browseButton")
                        button.innerHTML = "Star"
                        octokit.activity.unstarRepo({
                            owner: user,
                            repo: repoName
                        })
                    })
                        
                }).then(() =>{ 
                    var button= document.getElementById("Star-button")
                    button.setAttribute("class","liked")
                    button.innerHTML = "Starred"
                    octokit.activity.starRepo({
                        owner: user,
                        repo: repoName
                    })
                })
            })
        })
    }
    /** 
     * Fork a project on github by unique ID.
     */
    this.forkByID = function(id){
        
        //Authenticate - Initialize with OAuth.io app public key
        OAuth.initialize('BYP9iFpD7aTV9SDhnalvhZ4fwD8')
        // Use popup for oauth
        OAuth.popup('github').then(github => {

            octokit = new Octokit({
                auth: github.access_token
            })
            
            octokit.request('GET /repositories/:id', {id}).then(result => {
                //Find out the information of who owns the project we are trying to fork
                var user     = result.data.owner.login
                var repoName = result.data.name
                
                octokit.repos.listTopics({
                    owner: user, 
                    repo: repoName,
                    headers: {
                        accept: 'application/vnd.github.mercy-preview+json'
                    }
                }).then(result => {
                    var topics = result.data.names
                    
                    //Create a fork of the project with the found user name and repo name under your account
                    octokit.repos.createFork({
                        owner: user, 
                        repo: repoName,
                        headers: {
                            accept: 'application/vnd.github.mercy-preview+json'
                        }
                    }).then(result => {
                        var repoName = result.data.name
                        //Manually copy over the topics which are lost in forking
                        octokit.repos.replaceTopics({
                            owner: result.data.owner.login,
                            repo: result.data.name,
                            names: topics,
                            headers: {
                                accept: 'application/vnd.github.mercy-preview+json'
                            }
                        }).then(() => {
                            
                            //Remove everything in the popup now
                            while (popup.firstChild) {
                                popup.removeChild(popup.firstChild)
                            }
                            
                            popup.classList.remove('off')
                            popup.setAttribute("style", "text-align: center")

                            var subButtonDiv = document.createElement('div')
                            subButtonDiv.setAttribute("class", "form")
                            
                            //Add a title
                            var title = document.createElement("H3")
                            title.appendChild(document.createTextNode("A copy of the project '" + repoName + "' has been copied and added to your projects. You can view it by clicking the button below."))
                            subButtonDiv.setAttribute('style','color:white;')
                            subButtonDiv.appendChild(title)
                            subButtonDiv.appendChild(document.createElement("br"))
                            
                            var form = document.createElement("form")
                            subButtonDiv.appendChild(form)
                            var button = document.createElement("button")
                            button.setAttribute("type", "button")
                            button.setAttribute("style", "border:2px solid white;")
                            button.appendChild(document.createTextNode("View Projects"))
                            button.addEventListener("click", () => {
                                window.location.href = '/'
                            })
                            form.appendChild(button)
                            popup.appendChild(subButtonDiv)
                        })
                    })
                })
            })
        })
    }
    
    /** 
     * Upload or remove files from github. Files with null content will be deleted.
     * @param {object} files A dictionary with paths as keys and the content as the answer.
     */
    this.uploadAFile = async function(files){
        
        await this.createCommit(octokit,{
            owner: currentUser,
            repo: currentRepoName,
            changes: {
                files: files,
                commit: 'Upload file'
            }
        })
    }
    
    /** 
     * Get a file from github. Calback is called after the retrieved.
     */
    this.getAFile = async function(filePath){
        
        const result = await octokit.repos.getContent({
            owner: currentUser,
            repo: currentRepoName,
            path: filePath
        })
        
        //content will be base64 encoded
        let rawFile = atob(result.data.content)
        return rawFile
    }
    
    /** 
     * Get a link to the raw version of a file on GitHub
     */
    this.getAFileRawPath = function(filePath){
        const rawPath = "https://raw.githubusercontent.com/" + currentUser + "/" + currentRepoName + "/main/" + filePath
        return rawPath
    }
    
}