# Simple workflow for running puppeter tests on pull requests
name: Puppeteer Tests

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Install Puppeteer Chromium
        run: npx puppeteer install
      - name: build
        run: npm run build
      - name: Start server
        run: npm start &
      - name: Run Tests
        run: npm test
      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: puppeteer-screenshot
          path: Puppet/images/main.png
